-- Neutralized: this migration previously seeded a demo account
-- (a demo address) with a hardcoded, publicly-known password. Because
-- `wrangler d1 migrations apply --remote` runs every migration, that account
-- would be recreated in PRODUCTION on any fresh/restored database — a backdoor.
--
-- Dev seed data now lives in seeds/dev-seed.sql (local-only, never a migration):
--   npx wrangler d1 execute time-tracker --local --file=seeds/dev-seed.sql
--
-- Kept as a no-op (not deleted) so the D1 migration ledger / numbering stays
-- intact. The statement below is valid SQL that affects no rows.
SELECT 1 WHERE 0;
